/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './hooks/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
    '../../packages/ui/src/**/*.{ts,tsx}',
    '../../packages/utils/src/**/*.{ts,tsx}',
  ],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        'bg-base': 'var(--bg-base)',
        'bg-surface': 'var(--bg-surface)',
        'bg-elevated': 'var(--bg-elevated)',
        'bg-overlay': 'var(--bg-overlay)',
        'border-subtle': 'var(--border-subtle)',
        'border-default': 'var(--border-default)',
        'border-strong': 'var(--border-strong)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-tertiary': 'var(--text-tertiary)',
        'text-inverse': 'var(--text-inverse)',
        'accent-primary': 'var(--accent-primary)',
        'accent-warm': 'var(--accent-warm)',
        'accent-cool': 'var(--accent-cool)',
        'status-success': 'var(--status-success)',
        'status-warning': 'var(--status-warning)',
        'status-error': 'var(--status-error)',
        'status-info': 'var(--status-info)',
        'gen-queued': 'var(--gen-queued)',
        'gen-processing': 'var(--gen-processing)',
        'gen-done': 'var(--gen-done)',
        'gen-error': 'var(--gen-error)',
      },
      fontFamily: {
        display: ['Canela', 'Freight Display', 'Georgia', 'serif'],
        heading: ['"Suisse Int\'l Mono"', 'JetBrains Mono', 'monospace'],
        body: ['Söhne', 'Aktiv Grotesk', 'Helvetica Neue', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        '2xs': ['0.6875rem', { lineHeight: '1.3' }],
        xs: ['0.8125rem', { lineHeight: '1.4' }],
        base: ['0.9375rem', { lineHeight: '1.5' }],
        md: ['1.0625rem', { lineHeight: '1.5' }],
        lg: ['1.25rem', { lineHeight: '1.4' }],
        xl: ['1.5rem', { lineHeight: '1.3' }],
        '2xl': ['2rem', { lineHeight: '1.2' }],
        '3xl': ['2.75rem', { lineHeight: '1.1' }],
        '4xl': ['3.75rem', { lineHeight: '1.1' }],
        '5xl': ['5rem', { lineHeight: '1.1' }],
      },
      spacing: {
        '0.5': '0.125rem',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
        '10': '2.5rem',
        '12': '3rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '32': '8rem',
      },
      borderRadius: {
        sm: '2px',
        md: '6px',
        lg: '12px',
        xl: '20px',
        full: '9999px',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        'glow-gold': 'var(--glow-gold)',
      },
      animation: {
        'card-in': 'card-in 300ms ease-out',
        'result-reveal': 'result-reveal 600ms ease-out',
        shimmer: 'shimmer 1.5s infinite',
        'pulse-glow': 'pulse-glow 2s infinite',
        'fade-in': 'fade-in 200ms ease-out',
        'slide-up': 'slide-up 300ms ease-out',
        'spin-slow': 'spin 0.8s linear infinite',
      },
      keyframes: {
        'card-in': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'result-reveal': {
          '0%': { opacity: '0', transform: 'scale(0.96)', filter: 'blur(8px)' },
          '60%': { filter: 'blur(0)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        shimmer: {
          from: { backgroundPosition: '-200% 0' },
          to: { backgroundPosition: '200% 0' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(212,168,83,0)' },
          '50%': { boxShadow: '0 0 12px 2px rgba(212,168,83,0.3)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1440px',
      },
      maxWidth: {
        grid: '1440px',
      },
    },
  },
  plugins: [],
}
